### ISSUE TITLE
npm: command not found

### ISSUE THREAD

**Issue by yunus-alkan** [avatsaev/angular4-docker-example#1]
I guess you forgot installing of npm in Dockerfile?

**Comment by avatsaev** [comment]
Seems to be working fine, what version of docker are you using?

![screenshot from 2017-06-22 20-37-34](https://user-images.githubusercontent.com/518974/27450079-d435c740-578a-11e7-9e6b-c1342cf72f95.png)

![screenshot from 2017-06-22 20-38-31](https://user-images.githubusercontent.com/518974/27450078-d41f8f84-578a-11e7-833e-278809d0dfae.png)

**Comment by avatsaev** [comment]
Can't reproduce, closing.
