### ISSUE TITLE
Builds Fails On DockerHub

### ISSUE THREAD

**Issue by kigsmtua** [avatsaev/angular4-docker-example#6]
It seems that Docker hub does not understand what --from builder(as used in the Dockerfile) is

**Comment by avatsaev** [comment]
Not sure about docker hub but Docker Engine must be at minimum v17.05 on the host that is building the container

**Comment by kigsmtua** [comment]
@avatsaev Hub is running on  docker 17.06

**Comment by avatsaev** [comment]
Do you have the error trace?

**Comment by kigsmtua** [comment]
@avatsaev
`Build failed: Error parsing reference: "node:6.10 as builder" is not a valid repository/tag: invalid 
 reference format`

**Comment by avatsaev** [comment]
Ok, so apparently docker hub doesn't support multi stage builds yet, there is an open issue for that https://github.com/docker/hub-feedback/issues/1039 

So I'm closing this one.
